server:
  port: 9082

spring:
  application:
    name: device-processor-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: device-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

# MQTT Configuration
mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
  client:
    id: device-processor
  ssl:
    enabled: true
    truststore:
      path: classpath:certs/truststore.jks
      password: ${MQTT_STORE_PASS}
      type: JKS
    keystore:
      path: classpath:certs/keystore.jks
      password: ${MQTT_STORE_PASS}
      type: JKS
    protocol: TLSv1.2

# InfluxDB Configuration
influxdb:
  url: ${INFLUXDB_URL}
  token: ${INFLUXDB_TOKEN}
  org: ${INFLUXDB_ORG}
  bucket: ${INFLUXDB_BUCKET}

#
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.iot.deviceprocessor: ${LOG_LEVEL}
    org.springframework.kafka: INFO
    org.eclipse.paho: INFO
